name = "Associates"
uuid = "cbd430ec-77ce-45a7-8a10-accba12b1c72"
authors = ["Leo Breston <leo.breston@gmail.com> and contributors"]
version = "0.1.0"

[compat]
julia = "1"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
